version: '3.9'
services:
  app:
    image: python:3.10-alpine
    container_name: python-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "pip install -r requirements.txt && python main.py"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis-server
    ports:
      - "6379:6379"

